<?php
return [
    ["id" => '114', "title" =>' 免费体验', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '401', "title" => '广东题库', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '404', "title" => '济南题库', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '402', "title" => '浙江题库', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '405', "title" => '上海题库', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '403', "title" => '四川题库', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '406', "title" => '武汉题库', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '101', "title" =>'入门试题', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '111', "title" =>'考前强化题', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '102', "title" =>'必学题一', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '131', "title" =>'选学题一', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '103', "title" =>'必学题二', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '132', "title" =>'选学题二', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '104', "title" =>'必学题三', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '133', "title" =>'选学题三', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '105', "title" =>'必学题四', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '134', "title" =>'选学题四', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '106', "title" =>'必学题五', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '135', "title" =>'选学题五', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '151', "title" => '2020新题', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '136', "title" =>'选学题六', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" => '90100', "title" => '2020新题', 'car_type' => '小车', 'subject_type' => '科目一'],
    ["id" =>'219', "title" => '免费体验', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'137', "title" => '精选多选题', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'211', "title" => '入门试题', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'201', "title" => '考前强化题', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'202', "title" => '必学题一', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'231', "title" => '选学题一', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'203', "title" => '必学题二', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'232', "title" => '选学题二', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'204', "title" => '必学题三', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'233', "title" => '选学题三', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'205', "title" => '必学题四', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'234', "title" => '选学题四', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'206', "title" => '必学题五', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'235', "title" => '选学题五', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'251', "title" => '2020新题', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'90200', "title" => '2020新题', 'car_type' => '小车', 'subject_type' => '科目四'],
    ["id" =>'114', "title" => '免费体验', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'101', "title" => '入门试题', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'111', "title" => '考前强化题', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'102', "title" => '必学题一', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'131', "title" => '选学题一', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'103', "title" => '必学题二', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'132', "title" => '选学题二', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'104', "title" => '必学题三', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'133', "title" => '选学题三', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'105', "title" => '必学题四', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" =>'134', "title" => '选学题四', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" => '106', "title" => '必学题五', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" => '135', "title" => '选学题五', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" => '121', "title" => '货车专用', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" => '136', "title" => '选学题六', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" => '151', "title" => '2020新题', 'car_type' => '货车', 'subject_type' => '科目一'],
    ["id" => '219', "title" => '免费体验', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '137', "title" => '精选多选题', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '211', "title" => '入门试题', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '201', "title" => '考前强化题', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '202', "title" => '必学题一', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '231', "title" => '选学题一', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '203', "title" => '必学题二', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '232', "title" => '选学题二', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '204', "title" => '必学题三', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '233', "title" => '选学题三', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '205', "title" => '必学题四', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '234', "title" => '选学题四', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '206', "title" => '必学题五', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '235', "title" => '选学题五', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '121', "title" => '货车专用', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '251', "title" => '2020新题', 'car_type' => '货车', 'subject_type' => '科目四'],
    ["id" => '101', "title" => '入门试题', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '111', "title" => '考前强化题', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '102', "title" => '必学题一', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '131', "title" => '选学题一', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '103', "title" => '必学题二', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '132', "title" => '选学题二', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '104', "title" => '必学题三', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '133', "title" => '选学题三', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '105', "title" => '必学题四', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '134', "title" => '选学题四', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '106', "title" => '必学题五', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '135', "title" => '选学题五', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '122', "title" => '客车专用', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '136', "title" => '选学题六', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '151', "title" => '2020新题', 'car_type' => '客车', 'subject_type' => '科目一'],
    ["id" => '219', "title" => '免费体验', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '137', "title" => '精选多选题', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '211', "title" => '入门试题', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '201', "title" => '考前强化题', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '202', "title" => '必学题一', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '231', "title" => '选学题一', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '203', "title" => '必学题二', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '232', "title" => '选学题二', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '204', "title" => '必学题三', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '233', "title" => '选学题三', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '205', "title" => '必学题四', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '234', "title" => '选学题四', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '206', "title" => '必学题五', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '235', "title" => '选学题五', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '122', "title" => '客车专用', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '251', "title" => '2020新题', 'car_type' => '客车', 'subject_type' =>'科目四'],
    ["id" => '70701', "title" => '危险货物运输相关法律、法规常识', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70702', "title" => '社会责任和职业道德', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70703', "title" => '常见危险货物分类和特性', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70704', "title" => '危险货物运输包装知识', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70705', "title" => '道路危险货物运输车辆基本要求', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70706', "title" => '危险货物运输押运安全知识', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70707', "title" => '危险货物装卸安全知识', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70708', "title" => '常见危险货物应急处理措施', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70801', "title" => '危险货物运输相关法律、法规常识', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70802', "title" => '社会责任和职业道德', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70803', "title" => '常见危险货物的分类和相关特性', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70804', "title" => '危险货物运输包装知识', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70805', "title" => '道路危险货物运输车辆基本要求', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70806', "title" => '安全意识与安全行车', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70807', "title" => '常见危险货物应急处理措施', 'car_type' => '危险品押运员', 'subject_type' => '资格证'],
    ["id" => '70701', "title" => '危险货物运输相关法律、法规常识', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70702', "title" => '社会责任和职业道德', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70703', "title" => '常见危险货物分类和特性', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70704', "title" => '危险货物运输包装知识', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70705', "title" => '道路危险货物运输车辆基本要求', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70706', "title" => '危险货物运输押运安全知识', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70707', "title" => '危险货物装卸安全知识', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70708', "title" => '常见危险货物应急处理措施', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70801', "title" => '危险货物运输相关法律、法规常识', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70802', "title" => '社会责任和职业道德', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70803', "title" => '常见危险货物的分类和相关特性', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70804', "title" => '危险货物运输包装知识', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70805', "title" => '道路危险货物运输车辆基本要求', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70806', "title" => '安全意识与安全行车', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70807', "title" => '常见危险货物应急处理措施', 'car_type' => '危险品驾驶员', 'subject_type' => '资格证'],
    ["id" => '70301', "title" => '职业道德和法律法规', 'car_type' => '客运车', 'subject_type' => '资格证'],
    ["id" => '70302', "title" => '安全行车', 'car_type' => '客运车', 'subject_type' => '资格证'],
    ["id" => '70303', "title" => '应急处置和紧急救护', 'car_type' => '客运车', 'subject_type' => '资格证'],
    ["id" => '70304', "title" => '汽车使用技术', 'car_type' => '客运车', 'subject_type' => '资格证'],
    ["id" => '70305', "title" => '客运知识', 'car_type' => '客运车', 'subject_type' => '资格证'],
    ["id" => '70201', "title" => '职业道德和法律法规', 'car_type' => '货运车', 'subject_type' => '资格证'],
    ["id" => '70202', "title" => '安全行车', 'car_type' => '货运车', 'subject_type' => '资格证'],
    ["id" => '70203', "title" => '应急处置和紧急救护', 'car_type' => '货运车', 'subject_type' => '资格证'],
    ["id" => '70204', "title" => '汽车使用技术', 'car_type' => '货运车', 'subject_type' => '资格证'],
    ["id" => '70205', "title" => '货运知识', 'car_type' => '货运车', 'subject_type' => '资格证'],
    ["id" => '70101', "title" => '教练员职责', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70102', "title" => '道路交通安全法律法规', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70103', "title" => '道路运输法律法规', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70104', "title" => '交通安全心理与安全意识', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70105', "title" => '教育学教育心理学及其应用', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70106', "title" => '驾驶员培训教学大纲', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70107', "title" => '教学方法及规范化教学', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70108', "title" => '教学手段', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70109', "title" => '教案的编写', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70110', "title" => '典型交通事故案例分析', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70111', "title" => '车辆结构与安全性能', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70112', "title" => '车辆维护与故障处理', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70113', "title" => '车辆安全检视', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70114', "title" => '环保与节能驾驶', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70115', "title" => '特殊环境安全驾驶方法', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70116', "title" => '应急驾驶', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70117', "title" => '事故现场应急处理', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70118', "title" => '驾驶职业道德与文明驾驶知识', 'car_type' => '教练员', 'subject_type' => '资格证'],
    ["id" => '70501', "title" => '职业道德与服务规范', 'car_type' => '出租车', 'subject_type' => '资格证'],
    ["id" => '70502', "title" => '安全运营与治安防范', 'car_type' => '出租车', 'subject_type' => '资格证'],
    ["id" => '70503', "title" => '汽车使用与常见故障处理', 'car_type' => '出租车', 'subject_type' => '资格证'],
    ["id" => '70504', "title" => '节能驾驶', 'car_type' => '出租车', 'subject_type' => '资格证'],
    ["id" => '70505', "title" => '运价知识与计价器使用', 'car_type' => '出租车', 'subject_type' => '资格证'],
    ["id" => '70506', "title" => '道路交通事故处理与应急救护', 'car_type' => '出租车', 'subject_type' => '资格证'],
    ["id" => '70507', "title" => '出租车汽车政策、法规、标准', 'car_type' => '出租车', 'subject_type' => '资格证'],
    ["id" => '70508', "title" => '出租车服务质量信誉考核', 'car_type' => '出租车', 'subject_type' => '资格证'],
    ["id" => '70501', "title" => '职业道德与服务规范', 'car_type' => '网约车', 'subject_type' => '资格证'],
    ["id" => '70502', "title" => '安全运营与治安防范', 'car_type' => '网约车', 'subject_type' => '资格证'],
    ["id" => '70503', "title" => '汽车使用与常见故障处理', 'car_type' => '网约车', 'subject_type' => '资格证'],
    ["id" => '70504', "title" => '节能驾驶', 'car_type' => '网约车', 'subject_type' => '资格证'],
    ["id" => '70505', "title" => '运价知识与计价器使用', 'car_type' => '网约车', 'subject_type' => '资格证'],
    ["id" => '70506', "title" => '道路交通事故处理与应急救护', 'car_type' => '网约车', 'subject_type' => '资格证'],
    ["id" => '70507', "title" => '出租车汽车政策、法规、标准', 'car_type' => '网约车', 'subject_type' => '资格证'],
    ["id" => '70508', "title" => '出租车服务质量信誉考核', 'car_type' => '网约车', 'subject_type' => '资格证'],
    ["id" => '70600', "title" => '网约车资格证', 'car_type' => '网约车', 'subject_type' => '资格证'],
];
